### ISSUE TITLE
Is the wiki available

### ISSUE THREAD

**Issue by markdane** [labsyspharm/Visinity#10]
Hi, I saw mention of a wiki for VISINITY but do not see it in the repo. Is that or other user documentation available?

**Comment by simonwarchol** [comment]
Hey @markdane,
There is some general information in the https://github.com/labsyspharm/minerva_analysis repo, though it is less specific to Visinity. Apologies for the sparse documentation. I have some time next week and will bolster it a bit in preparation for presenting it @ IEEE VIS. IS there anything specifically you're confused about that I can clear up in the meantime? :) 
-Simon

**Comment by markdane** [comment]
Hi Simon

Thanks for the response and great app. I’ve tried to match the format of my input files to those in the example data set but am getting dictionary index errors from the phenotype dict. (I’m away from my computer now so I don’t have more details).

It would be useful to have detailed specs on the input files. I think I may be having issues with the image and mask files. Do these both need to be ome.tif files? What metadata, data types, organization etc do they need? How do the coordinates in the quantification file match the cellid in the tif files? I suspect some of these may be covered in the Minerva docs and will review that when I’m back at my computer.

Best
Mark


[OHSU email via VMware Boxer]

On September 29, 2022 at 7:15:53 AM PDT, Simon Warchol ***@***.***> wrote:

Hey @markdane<https://urldefense.com/v3/__https://github.com/markdane__;!!Mi0JBg!OxHbI-mjlOUgXeS3C8868OKtENMkce5Q5r5VH98xpgIiiYEzsja5zZKTvd-RjRNcHX-_9vvOU8oK7-FAI5uKPQ$>,
There is some general information in the https://github.com/labsyspharm/minerva_analysis<https://urldefense.com/v3/__https://github.com/labsyspharm/minerva_analysis__;!!Mi0JBg!OxHbI-mjlOUgXeS3C8868OKtENMkce5Q5r5VH98xpgIiiYEzsja5zZKTvd-RjRNcHX-_9vvOU8oK7-GUjLbeug$> repo, though it is less specific to Visinity. Apologies for the sparse documentation. I have some time next week and will bolster it a bit in preparation for presenting it @ IEEE VIS. IS there anything specifically you're confused about that I can clear up in the meantime? :)
-Simon

**Comment by markdane** [comment]
Simon,
I want to evaluate Visinity for analyzing  Nanostring RNA data. The RNA data have the abundance and of 980 types of genes associated with each cell. There is also a 5 channel IF image, labeled masks and the metadata. 

I've converted the image and masks to OME tiff files and matched my csv files to the sample file formats but am getting various errors based on which variation of formats I try.  Do you have any experience with Nanostring data?  I didn't find file format information in the Minerva documents that helped me move forward.

**Comment by simonwarchol** [comment]
Hey Mark,
The change I just pushed this morning actually should address the phenotype dict issues you're seeing in the previous comment.
Is there an equivalently formatted dataset hosted anywhere I could try things out with? Let me check with other members of the minerva team and see if they know more and I'll respond here.
-Simon

**Comment by markdane** [comment]
I used the Lung 5-2 dataset in another pipeline and that worked well. I did retry with the new code this morning and made further progress. When I load the data the GUI eventually goes back to the home screen with choices of Data source or upload. I then choose the new data using Data source and it seems to begin building an image line by line in the center panel. I get a big set of the messages below with different png files in the first line.

ERROR:minerva_analysis:Exception on /generated/data/Oct5_0/CellLabels_filtered_F012/0/0_1553.png [GET]
Traceback (most recent call last):
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/routes/data_routes.py", line 402, in generate_png
    png = data_model.generate_zarr_png(datasource, channel, level, tile)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/models/data_model.py", line 1341, in generate_zarr_png
    tile = tile.view('uint8').reshape(tile.shape + (-1,))[..., [0, 1, 2]]
IndexError: index 2 is out of bounds for axis 2 with size 2

**Comment by simonwarchol** [comment]
Ok cool will try out this data now.

**Comment by simonwarchol** [comment]
Are you using files from this https://nanostring-public-share.s3.us-west-2.amazonaws.com/SMI-Compressed/Lung5_Rep2/Lung5_Rep2+SMI+Flat+data.tar.gz as the image or one of the "Raw Morphological Images".

**Comment by markdane** [comment]
I used files that are the same format as those but our own data (which is PHI data and I can't share it). I also tried using ImageJ to convert the labels to be ome.tif and to match the datatype in your sample data.

Perhaps I should try to recreate my problems with the publicly available data.

**Comment by markdane** [comment]
I also processed my csv files to match the format of your example data. I'll put the publicly available data through that pipeline and share it.

**Comment by markdane** [comment]
@simonwarchol  I've processed a set of Nanostring files and am getting the same error as on my own files. I'm attaching the csv files to go with fov12 of the Lung5_Rep2 sample. The image files are too big to attach here but I believe you have them from the "Raw MorphologicalImages" section on the Nanostring website.


Appending input images
    1: /Users/dane/Library/CloudStorage/OneDrive-OregonHealth&ScienceUniversity/Documents_cloud/CosMx/python/tutorial_data/nanostring_data/Lung5_Rep2/Lung5_Rep2-Flat_files_and_images/CellLabels_F012.ome.tif

Pyramid level sizes:
    level 1: 5472x3648 (original size)
    level 2: 2736x1824
    level 3: 1368x912
    level 4: 684x456

Resizing channels for level 2 (5472x3648 -> 2736x1824)
    1: 100%ERROR:minerva_analysis:Exception on /upload [POST]
Traceback (most recent call last):
  File "/Users/dane/Documents/visinity/minerva_analysis/server/routes/import_routes.py", line 234, in upload_file_page
    label_info = data_model.convertOmeTiff(labelFile, channelFilePath=channelFile,
  File "/Users/dane/Documents/visinity/minerva_analysis/server/models/data_model.py", line 1458, in convertOmeTiff
    pyramid_assemble.main(py_args=args)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/utils/pyramid_assemble.py", line 273, in main
    imsave(out_path, img_out, tile_size)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/utils/pyramid_assemble.py", line 42, in imsave
    tifffile.imwrite(
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/tifffile/tifffile.py", line 856, in imwrite
    result = tif.write(data, shape, dtype, **kwargs)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/tifffile/tifffile.py", line 1614, in write
    self._ome = OmeXml(**metadata)
TypeError: type object argument after ** must be a mapping, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/routes/import_routes.py", line 278, in upload_file_page
    return render_template('index.html')
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dane/Documents/visinity/minerva_analysis/client/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/dane/Documents/visinity/minerva_analysis/client/templates/base.html", line 27, in top-level template code
    window.flaskVariables = passVariablesToFrontend({{data|tojson}});
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/jinja2/filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/jinja2/utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Undefined is not JSON serializable
Percentage: -50 -1 2 type object argument after ** must be a mapping, not NoneType
[Lung5_Rep2_IF_quantification_file.csv](https://github.com/labsyspharm/Visinity/files/9719490/Lung5_Rep2_IF_quantification_file.csv)
[Lung5_Rep2_phenotypes_file.csv](https://github.com/labsyspharm/Visinity/files/9719493/Lung5_Rep2_phenotypes_file.csv)

**Comment by simonwarchol** [comment]
Hey @markdane,
Ah ok i see the issue -- It's looking for OME XML metadata in the segmentation mask and not finding it. I can quickly write a catch for that.
-Simon

**Comment by simonwarchol** [comment]
@markdane can you try renaming the segmentation mask `CellLabels_F012.tif` instead of `CellLabels_F012.ome.tif`. These files are just regular tifs and tifffile is looking for that ome XML inside them when it has the extension.

**Comment by markdane** [comment]
@simonwarchol I continue to get the same error in the terminal window while the image builds line by line in the center of the Visinity console. My process is to select one of the 5 channel images from the Raw Morphological set, open it with ImageJ, use show properties to make it have 5 channels instead of 5 slices, use the BioFormats plugin to export the image as an OME.tif file. I use the corresponding CellOverlay file as downloaded from the website. Previously I was converting these to OME.tif files but I'm not doing that here. I also input the two csv files attached here. The quatification file is different from the one I posted earlier.

The upload doesn't generate any errors. It's when I choose the data under Data Sources that I get the full set of panels, errors in the terminal window and the growing line-by-line image in the center panel.

[Lung5_Rep2_IF_quantification_file.csv](https://github.com/labsyspharm/Visinity/files/9735183/Lung5_Rep2_IF_quantification_file.csv)
[Lung5_Rep2_phenotypes_file.csv](https://github.com/labsyspharm/Visinity/files/9735185/Lung5_Rep2_phenotypes_file.csv)

ERROR:minerva_analysis:Exception on /generated/data/Oct7_lung5_rep2_4/CellLabels_F012/0/0_2097.png [GET]
Traceback (most recent call last):
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dane/opt/miniconda3/envs/visinity/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/routes/data_routes.py", line 402, in generate_png
    png = data_model.generate_zarr_png(datasource, channel, level, tile)
  File "/Users/dane/Documents/visinity/minerva_analysis/server/models/data_model.py", line 1341, in generate_zarr_png
    tile = tile.view('uint8').reshape(tile.shape + (-1,))[..., [0, 1, 2]]
IndexError: index 2 is out of bounds for axis 2 with size 2

**Comment by simonwarchol** [comment]
Hey Mark,
Sorry completely missed this. This is a really strange error -- it's trying to split the bits of the segmentation tiff into the 3 PNG channels but can't. What's this is using `CellLabels_F012.tif` right? Any idea what the bitdepth is?
-Simon

**Comment by markdane** [comment]
Hey Simon, These files are single channel, 16 bit unsigned integers.

**Comment by markdane** [comment]
@simonwarchol Can you describe what format these files should have? I'm making progress in other parts of my Nanostring CosMx RNA pipeline and think Visinity will be a great tool for evaluating the results.

**Comment by simonwarchol** [comment]
Hey @markdane,
Apologies for all the delays, I've been at a conference for the last week. I've finally been able to reproduce your issue and have pushed up a fix that seems to work on my end. Looks like most of the segmentation masks i've been dealing with are 32 bit, so i just had to do some casting. A new release should build in the next 30 min or so. Took me a while to wrangle the `Lung5_12` data (CSV format is weird with a cellid = 0 that seems to be a cumulative of the ROI and non-ome image stacks divided into 5 channels per file) but i think if you made it as far as that error things should be alright.
Let me know if you see any other issues, I'm free to meet on Tuesday any time if you need any more help.
-Simon

**Comment by markdane** [comment]
@simonwarchol If you're still available,  I would like to meet on Tuesday any time outside of 11-12 west coast time.
