### ISSUE TITLE
sqlalchemy has no attribute '__all__'

### ISSUE THREAD

**Issue by kmkowale** [labsyspharm/Visinity#12]
Hi, I have been getting the following error when running the attempting to run visinity 0.95:
_________________________________________________________________________________________________
(visinity) C:\Users\karlm>python visinity\run.py
Traceback (most recent call last):
  File "visinity\run.py", line 5, in <module>
    from minerva_analysis import app
  File "C:\Users\karlm\visinity\minerva_analysis\__init__.py", line 25, in <module>
    db = SQLAlchemy(app)
  File "C:\Users\karlm\anaconda3\envs\visinity\lib\site-packages\flask_sqlalchemy\__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "C:\Users\karlm\anaconda3\envs\visinity\lib\site-packages\flask_sqlalchemy\__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'
________________________________________________________________________________________________
Is there a workaround for this issue? It happens when I use the exe file as well.
Thanks,
Karl

**Comment by shiverstalker** [comment]
The same goes for me :S. I tried upgrading Flask-SQLAlchemy via pip, but another problem surfaced.

**Comment by shiverstalker** [comment]
@simonwarchol thank youu! It works perfectly right now!
