### ISSUE TITLE
Conda installation fails on M1 mac

### ISSUE THREAD

**Issue by straussmaximilian** [labsyspharm/Visinity#9]
Hi,
just tried to install and run `visinity` on a M1-Mac and it failed.
- macOS Monterey (12.6)
- MacBookPro w. Apple M1 Max w. 64 GB
- conda 4.14.0 py39hca03da5_0

Leaving the log here FYI.
```
(base) user@COMPUTER visinity % conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
click-8.1.3          | 146 KB    | ####################################################################################################### | 100% 
itsdangerous-2.1.2   | 16 KB     | ####################################################################################################### | 100% 
libpng-1.6.38        | 297 KB    | ####################################################################################################### | 100% 
zarr-2.10.1          | 110 KB    | ####################################################################################################### | 100% 
typing_extensions-4. | 28 KB     | ####################################################################################################### | 100% 
llvmlite-0.38.1      | 240 KB    | ####################################################################################################### | 100% 
cytoolz-0.12.0       | 343 KB    | ####################################################################################################### | 100% 
libsqlite-3.39.3     | 802 KB    | ####################################################################################################### | 100% 
tifffile-2021.4.8    | 130 KB    | ####################################################################################################### | 100% 
libwebp-base-1.2.4   | 316 KB    | ####################################################################################################### | 100% 
cycler-0.11.0        | 10 KB     | ####################################################################################################### | 100% 
imageio-2.13.1       | 3.1 MB    | ####################################################################################################### | 100% 
pyinstaller-5.1      | 1.0 MB    | ####################################################################################################### | 100% 
libopenblas-0.3.21   | 3.9 MB    | ####################################################################################################### | 100% 
libcblas-3.9.0       | 13 KB     | ####################################################################################################### | 100% 
matplotlib-3.6.0     | 7 KB      | ####################################################################################################### | 100% 
brotlipy-0.7.0       | 341 KB    | ####################################################################################################### | 100% 
libgfortran-5.0.0    | 146 KB    | ####################################################################################################### | 100% 
kiwisolver-1.4.4     | 62 KB     | ####################################################################################################### | 100% 
numba-0.55.2         | 3.8 MB    | ####################################################################################################### | 100% 
urllib3-1.26.11      | 102 KB    | ####################################################################################################### | 100% 
libblas-3.9.0        | 13 KB     | ####################################################################################################### | 100% 
flask-2.1.0          | 70 KB     | ####################################################################################################### | 100% 
zstd-1.5.2           | 378 KB    | ####################################################################################################### | 100% 
numcodecs-0.10.2     | 996 KB    | ####################################################################################################### | 100% 
unicodedata2-14.0.0  | 503 KB    | ####################################################################################################### | 100% 
msgpack-python-1.0.4 | 81 KB     | ####################################################################################################### | 100% 
idna-3.4             | 55 KB     | ####################################################################################################### | 100% 
pyopenssl-22.0.0     | 120 KB    | ####################################################################################################### | 100% 
dask-core-2022.9.1   | 849 KB    | ####################################################################################################### | 100% 
requests-2.28.1      | 53 KB     | ####################################################################################################### | 100% 
typing-extensions-4. | 8 KB      | ####################################################################################################### | 100% 
markupsafe-2.1.1     | 22 KB     | ####################################################################################################### | 100% 
jinja2-3.1.2         | 99 KB     | ####################################################################################################### | 100% 
threadpoolctl-3.1.0  | 18 KB     | ####################################################################################################### | 100% 
libcxx-14.0.6        | 1.3 MB    | ####################################################################################################### | 100% 
toolz-0.12.0         | 48 KB     | ####################################################################################################### | 100% 
pandas-1.5.0         | 12.1 MB   | ####################################################################################################### | 100% 
c-blosc2-2.4.1       | 228 KB    | ####################################################################################################### | 100% 
flask-sqlalchemy-2.5 | 19 KB     | ####################################################################################################### | 100% 
hdbscan-0.8.28       | 521 KB    | ####################################################################################################### | 100% 
importlib-metadata-4 | 33 KB     | ####################################################################################################### | 100% 
pytz-2022.2.1        | 224 KB    | ####################################################################################################### | 100% 
sqlite-3.39.3        | 794 KB    | ####################################################################################################### | 100% 
sqlalchemy-1.4.41    | 2.4 MB    | ####################################################################################################### | 100% 
pillow-8.1.1         | 635 KB    | ####################################################################################################### | 100% 
liblapack-3.9.0      | 13 KB     | ####################################################################################################### | 100% 
readline-8.1.2       | 263 KB    | ####################################################################################################### | 100% 
pysocks-1.7.1        | 19 KB     | ####################################################################################################### | 100% 
macholib-1.16.2      | 36 KB     | ####################################################################################################### | 100% 
ca-certificates-2022 | 150 KB    | ####################################################################################################### | 100% 
libgfortran5-11.3.0  | 1.3 MB    | ####################################################################################################### | 100% 
certifi-2022.9.24    | 155 KB    | ####################################################################################################### | 100% 
freetype-2.12.1      | 852 KB    | ####################################################################################################### | 100% 
matplotlib-base-3.6. | 7.4 MB    | ####################################################################################################### | 100% 
munkres-1.1.4        | 12 KB     | ####################################################################################################### | 100% 
pyinstaller-hooks-co | 95 KB     | ####################################################################################################### | 100% 
scikit-image-0.19.3  | 10.9 MB   | ####################################################################################################### | 100% 
fsspec-2022.8.2      | 96 KB     | ####################################################################################################### | 100% 
openjpeg-2.5.0       | 447 KB    | ####################################################################################################### | 100% 
scipy-1.9.1          | 21.8 MB   | ####################################################################################################### | 100% 
contourpy-1.0.5      | 230 KB    | ####################################################################################################### | 100% 
dav1d-1.0.0          | 423 KB    | ####################################################################################################### | 100% 
setuptools-65.4.0    | 731 KB    | ####################################################################################################### | 100% 
libtiff-4.3.0        | 574 KB    | ####################################################################################################### | 100% 
python_abi-3.8       | 4 KB      | ####################################################################################################### | 100% 
numpy-1.22.4         | 5.8 MB    | ####################################################################################################### | 100% 
cffi-1.15.1          | 220 KB    | ####################################################################################################### | 100% 
cryptography-37.0.4  | 1.2 MB    | ####################################################################################################### | 100% 
orjson-3.8.0         | 258 KB    | ####################################################################################################### | 100% 
networkx-2.8.6       | 1.6 MB    | ####################################################################################################### | 100% 
scikit-learn-1.1.2   | 7.4 MB    | ####################################################################################################### | 100% 
altgraph-0.17.2      | 21 KB     | ####################################################################################################### | 100% 
zlib-1.2.12          | 80 KB     | ####################################################################################################### | 100% 
cloudpickle-2.2.0    | 25 KB     | ####################################################################################################### | 100% 
pywavelets-1.3.0     | 4.3 MB    | ####################################################################################################### | 100% 
fonttools-4.37.3     | 1.9 MB    | ####################################################################################################### | 100% 
waitress-2.1.2       | 46 KB     | ####################################################################################################### | 100% 
imagecodecs-2022.2.2 | 2.1 MB    | ####################################################################################################### | 100% 
aom-3.5.0            | 2.4 MB    | ####################################################################################################### | 100% 
libavif-0.10.1       | 85 KB     | ####################################################################################################### | 100% 
werkzeug-2.2.2       | 249 KB    | ####################################################################################################### | 100% 
greenlet-1.1.3       | 88 KB     | ####################################################################################################### | 100% 
joblib-1.2.0         | 205 KB    | ####################################################################################################### | 100% 
libzlib-1.2.12       | 51 KB     | ####################################################################################################### | 100% 
jpeg-9e              | 259 KB    | ####################################################################################################### | 100% 
pyyaml-6.0           | 161 KB    | ####################################################################################################### | 100% 
partd-1.3.0          | 18 KB     | ####################################################################################################### | 100% 
libllvm11-11.1.0     | 20.9 MB   | ####################################################################################################### | 100% 
charset-normalizer-2 | 36 KB     | ####################################################################################################### | 100% 
python-3.8.13        | 12.3 MB   | ####################################################################################################### | 100% 
tornado-6.2          | 655 KB    | ####################################################################################################### | 100% 
xz-5.2.6             | 230 KB    | ####################################################################################################### | 100% 
olefile-0.46         | 32 KB     | ####################################################################################################### | 100% 
libssh2-1.10.0       | 218 KB    | ####################################################################################################### | 100% 
zipp-3.8.1           | 13 KB     | ####################################################################################################### | 100% 
pip-22.2.2           | 1.5 MB    | ####################################################################################################### | 100% 
libnghttp2-1.47.0    | 816 KB    | ####################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/Users/flq567/miniconda3/envs/visinity/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt']
Pip subprocess output:
Collecting elementpath==2.3.2
  Downloading elementpath-2.3.2-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.5/155.5 kB 792.1 kB/s eta 0:00:00
Collecting pycave==3.1.3
  Downloading pycave-3.1.3-py3-none-any.whl (37 kB)
Collecting numpy-indexed
  Downloading numpy_indexed-0.3.5-py2.py3-none-any.whl (18 kB)
Collecting ome-types==0.2.9
  Downloading ome_types-0.2.9-py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 1.3 MB/s eta 0:00:00
Collecting opencv-python
  Downloading opencv_python-4.6.0.66-cp37-abi3-macosx_11_0_arm64.whl (30.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.0/30.0 MB 4.4 MB/s eta 0:00:00
Collecting umap-learn
  Downloading umap-learn-0.5.3.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting xmlschema==1.8.0
  Downloading xmlschema-1.8.0-py3-none-any.whl (262 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.1/262.1 kB 4.0 MB/s eta 0:00:00
Collecting torch<2.0.0,>=1.8.0
  Using cached torch-1.12.1-cp38-none-macosx_11_0_arm64.whl (49.1 MB)
Collecting pytorch-lightning<2.0.0,>=1.6.0
  Downloading pytorch_lightning-1.7.7-py3-none-any.whl (708 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 708.1/708.1 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.20.3 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (1.22.4)
Collecting torchmetrics<0.6.0,>=0.5.1
  Downloading torchmetrics-0.5.1-py3-none-any.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.0/283.0 kB 4.0 MB/s eta 0:00:00
Collecting lightkit<0.5.0,>=0.4.4
  Downloading lightkit-0.4.4-py3-none-any.whl (17 kB)
Collecting pydantic[email]>=1.0
  Using cached pydantic-1.10.2-cp38-cp38-macosx_11_0_arm64.whl (2.6 MB)
Collecting Pint>=0.15
  Using cached Pint-0.19.2-py3-none-any.whl
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Requirement already satisfied: scikit-learn>=0.22 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (1.1.2)
Requirement already satisfied: scipy>=1.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (1.9.1)
Requirement already satisfied: numba>=0.49 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (0.55.2)
Collecting pynndescent>=0.5
  Downloading pynndescent-0.5.7.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting tqdm
  Downloading tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from numba>=0.49->umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (0.38.1)
Requirement already satisfied: setuptools in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from numba>=0.49->umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (65.4.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pydantic[email]>=1.0->ome-types==0.2.9->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 4)) (4.3.0)
Collecting email-validator>=1.0.3
  Downloading email_validator-1.3.0-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: joblib>=0.11 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pynndescent>=0.5->umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (1.2.0)
Collecting tensorboard>=2.9.1
  Downloading tensorboard-2.10.1-py3-none-any.whl (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 5.2 MB/s eta 0:00:00
Collecting pytorch-lightning<2.0.0,>=1.6.0
  Downloading pytorch_lightning-1.7.6-py3-none-any.whl (707 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 707.5/707.5 kB 4.6 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.5-py3-none-any.whl (706 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.6/706.6 kB 4.6 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.4-py3-none-any.whl (706 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.5/706.5 kB 5.9 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.3-py3-none-any.whl (705 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.8/705.8 kB 5.6 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.2-py3-none-any.whl (705 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.6/705.6 kB 5.0 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.1-py3-none-any.whl (701 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.5/701.5 kB 6.1 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.7.0-py3-none-any.whl (700 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 700.9/700.9 kB 6.2 MB/s eta 0:00:00
  Downloading pytorch_lightning-1.6.5-py3-none-any.whl (585 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: packaging>=17.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (21.3)
Requirement already satisfied: PyYAML>=5.4 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (6.0)
Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2022.8.2)
Collecting protobuf<=3.20.1
  Using cached protobuf-3.20.1-py2.py3-none-any.whl (162 kB)
Collecting pyDeprecate>=0.3.1
  Using cached pyDeprecate-0.3.2-py3-none-any.whl (10 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from scikit-learn>=0.22->umap-learn->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 6)) (3.1.0)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.2.1-py3-none-any.whl (269 kB)
Requirement already satisfied: idna>=2.0.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from email-validator>=1.0.3->pydantic[email]>=1.0->ome-types==0.2.9->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 4)) (3.4)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.8.3-cp38-cp38-macosx_11_0_arm64.whl (337 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.4/337.4 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: requests in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from packaging>=17.0->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (3.0.9)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Requirement already satisfied: wheel>=0.26 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (0.37.1)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2.2.2)
Collecting grpcio>=1.24.3
  Downloading grpcio-1.49.1.tar.gz (22.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.1/22.1 MB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting protobuf<=3.20.1
  Downloading protobuf-3.19.5-py2.py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.7/162.7 kB 3.3 MB/s eta 0:00:00
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.11.1-py2.py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 2.3 MB/s eta 0:00:00
Collecting absl-py>=0.4
  Using cached absl_py-1.2.0-py3-none-any.whl (123 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.1-cp38-cp38-macosx_11_0_arm64.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 1.7 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp38-cp38-macosx_11_0_arm64.whl (29 kB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2.1.1)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.1-cp38-cp38-macosx_11_0_arm64.whl (35 kB)
Collecting attrs>=17.3.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: six>=1.9.0 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (1.16.0)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: importlib-metadata>=4.4 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from markdown>=2.6.8->tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (4.11.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from requests->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: zipp>=0.5 in /Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard>=2.9.1->pytorch-lightning<2.0.0,>=1.6.0->pycave==3.1.3->-r /Users/flq567/programming/visinity/condaenv.bszso9lo.requirements.txt (line 2)) (3.8.1)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.1-py3-none-any.whl (151 kB)
Building wheels for collected packages: umap-learn, pynndescent, grpcio
  Building wheel for umap-learn (setup.py): started
  Building wheel for umap-learn (setup.py): finished with status 'done'
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82814 sha256=dd6c56b492a80be0f651659fb0523d4f5997f046e78880b2c960c174d6224bfa
  Stored in directory: /Users/flq567/Library/Caches/pip/wheels/a9/3a/67/06a8950e053725912e6a8c42c4a3a241410f6487b8402542ea
  Building wheel for pynndescent (setup.py): started
  Building wheel for pynndescent (setup.py): finished with status 'done'
  Created wheel for pynndescent: filename=pynndescent-0.5.7-py3-none-any.whl size=54269 sha256=35f898d2009f14d440c6fcb50a1ed2c582cf60f4d6ce3f8586b72975f4534127
  Stored in directory: /Users/flq567/Library/Caches/pip/wheels/1b/38/fe/99e22fbae88abd1c5e8d99253cba6d1c590cc7a94408bff3bf
  Building wheel for grpcio (setup.py): started
  Building wheel for grpcio (setup.py): still running...
  Building wheel for grpcio (setup.py): finished with status 'done'
  Created wheel for grpcio: filename=grpcio-1.49.1-cp38-cp38-macosx_11_0_arm64.whl size=3341532 sha256=2cd748edd84a50e929854ac2e9da38130af525c4618171199f50cf4201bc47de
  Stored in directory: /Users/flq567/Library/Caches/pip/wheels/ae/75/9b/1cfee21306a9993817964b0c777cbedf8a42342254986cd0e9
Successfully built umap-learn pynndescent grpcio
Installing collected packages: tensorboard-plugin-wit, pyasn1, tqdm, torch, tensorboard-data-server, rsa, pyDeprecate, pydantic, pyasn1-modules, protobuf, Pint, opencv-python, oauthlib, multidict, grpcio, future, frozenlist, elementpath, dnspython, cachetools, attrs, async-timeout, absl-py, yarl, xmlschema, torchmetrics, requests-oauthlib, numpy-indexed, markdown, google-auth, email-validator, aiosignal, pynndescent, google-auth-oauthlib, aiohttp, umap-learn, tensorboard, ome-types, pytorch-lightning, lightkit, pycave
Successfully installed Pint-0.19.2 absl-py-1.2.0 aiohttp-3.8.3 aiosignal-1.2.0 async-timeout-4.0.2 attrs-22.1.0 cachetools-5.2.0 dnspython-2.2.1 elementpath-2.3.2 email-validator-1.3.0 frozenlist-1.3.1 future-0.18.2 google-auth-2.11.1 google-auth-oauthlib-0.4.6 grpcio-1.49.1 lightkit-0.4.4 markdown-3.4.1 multidict-6.0.2 numpy-indexed-0.3.5 oauthlib-3.2.1 ome-types-0.2.9 opencv-python-4.6.0.66 protobuf-3.19.5 pyDeprecate-0.3.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycave-3.1.3 pydantic-1.10.2 pynndescent-0.5.7 pytorch-lightning-1.6.5 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.10.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 torch-1.12.1 torchmetrics-0.5.1 tqdm-4.64.1 umap-learn-0.5.3 xmlschema-1.8.0 yarl-1.8.1

done
#
# To activate this environment, use
#
#     $ conda activate visinity
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) user@COMPUTER visinity % conda activate visinity
(visinity) user@COMPUTER visinity % python run.py
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from minerva_analysis import app
  File "/Users/flq567/programming/visinity/minerva_analysis/__init__.py", line 55, in <module>
    from minerva_analysis.server.routes import page_routes, data_routes, import_routes
  File "/Users/flq567/programming/visinity/minerva_analysis/server/routes/data_routes.py", line 6, in <module>
    from minerva_analysis.server.models import data_model
  File "/Users/flq567/programming/visinity/minerva_analysis/server/models/data_model.py", line 8, in <module>
    import hdbscan
  File "/Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/Users/flq567/miniconda3/envs/visinity/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 509, in <module>
    memory=Memory(cachedir=None, verbose=0),
TypeError: __init__() got an unexpected keyword argument 'cachedir'
(visinity) user@COMPUTER visinity % 
```

**Comment by simonwarchol** [comment]
Hey @straussmaximilian,
I'll take a look on an M1 mac today and report back / make any changes necessary. Sorry about that :)
-Simon

**Comment by markdane** [comment]
I had a similar or same problem and found the solution for mine. Maybe this will help https://github.com/labsyspharm/Visinity/issues?q=is%3Aissue+is%3Aclosed

**Comment by simonwarchol** [comment]
Hey @markdane, Appreciate you pointing this out. the hdbscan/sklearn community should push a fix soon which will resolve things, so will be on the lookout for this. I'll hardcode the joblib in the requirements file and push that up in a sec.
-Simon
